spring:
  kafka:
    bootstrap-servers: localhost:9092
    topics: infosys.rss
  data:
    mongodb:
      username: sachin
      password: '{cipher}7d146093387ef179c9b0c1f86c573d800d18bfb5a9ec13f69f6df61466b14296'
      database: feedDB
      host: 192.168.99.100
      port: 27017
      authentication-database: feedDB
db:
  collection:
    info: infy.feed
    
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8082/eureka
