spring:
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      username: sachin
      password: nexus
      database: feedDB
      host: localhost
      port: 27017
      authentication-database: feedDB
db:
  collection:
    info: infy.feed
    
eureka:
  client:
    service-url
      defaultZone: http://localhost:2222/eureka
