spring:
  application:
    name: discovery
    
# HTTP (Tomcat) port
server:
  port: 8082

# Configure this Discovery Server
# Not a client, don't register with yourself
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url.defaultZone: http://localhost:2222/eureka
