spring:
  application:
    name: discovery
    
# HTTP (Tomcat) port
server:
  port: 8082

# Configure this Discovery Server
# Not a client, don't register with yourself
eureka:
  instance:
    hostname: 192.168.99.100
  client:
    fetch-registry: false
    register-with-eureka: false
